// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PostCodes.Infrastructure.Context;

#nullable disable

namespace PostCodes.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220912102425_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PostCodes.Domain.Entities.PostCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AdminCounty")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("admin_county");

                    b.Property<string>("AdminDistrict")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("admin_district");

                    b.Property<string>("AdminWard")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("admin_ward");

                    b.Property<string>("Ccg")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ccg");

                    b.Property<string>("Ced")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ced");

                    b.Property<string>("CodeAdminCounty")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("code_admin_county");

                    b.Property<string>("CodeAdminDistrict")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("code_admin_district");

                    b.Property<string>("CodeAdminWard")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("code_admin_ward");

                    b.Property<string>("CodeCcg")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("code_ccg");

                    b.Property<string>("CodeCcgId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("code_ccg_id");

                    b.Property<string>("CodeLau2")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("code_lau2");

                    b.Property<string>("CodeLsoa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("code_lsoa");

                    b.Property<string>("CodeMsoa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("code_msoa");

                    b.Property<string>("CodeNuts")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("code_nuts");

                    b.Property<string>("CodeParish")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("code_parish");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("country");

                    b.Property<DateTime?>("Date")
                        .IsRequired()
                        .HasColumnType("datetime2")
                        .HasColumnName("date");

                    b.Property<double?>("DistanceToAirport")
                        .HasColumnType("float")
                        .HasColumnName("distance_to_airport");

                    b.Property<int?>("Eastings")
                        .HasColumnType("int")
                        .HasColumnName("eastings");

                    b.Property<string>("EuropeanElectoralRegion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("european_electoral_region");

                    b.Property<string>("Incode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("incode");

                    b.Property<float?>("Latitude")
                        .HasColumnType("real")
                        .HasColumnName("latitude");

                    b.Property<float?>("Longitude")
                        .HasColumnType("real")
                        .HasColumnName("longitude");

                    b.Property<string>("Lsoa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lsoa");

                    b.Property<string>("Msoa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("msoa");

                    b.Property<string>("NhsHa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nhs_ha");

                    b.Property<int?>("Northings")
                        .HasColumnType("int")
                        .HasColumnName("northings");

                    b.Property<string>("Nuts")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nuts");

                    b.Property<string>("Outcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("outcode");

                    b.Property<string>("Parish")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("parish");

                    b.Property<string>("ParliamentaryConstituency")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("parliamentary_constituency");

                    b.Property<string>("PostCodeNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("post_code_number");

                    b.Property<string>("PrimaryCareTrust")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("primary_care_trust");

                    b.Property<int>("Quality")
                        .HasColumnType("int")
                        .HasColumnName("quality");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("region");

                    b.HasKey("Id");

                    b.ToTable("post_code", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
